server:
  port: 80

spring:
  application:
    name: demo

  # =========================== ↓↓↓↓↓↓ 配置数据源 ↓↓↓↓↓↓ ===========================
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=false # MySQL在高版本需要指明是否进行SSL连接 解决则加上 &useSSL=false
    name: demo
    username: JASYPT_ZQ(N/+f2B9SznK4MUDSp24Upw==)
    password: JASYPT_ZQ(N/+f2B9SznK4MUDSp24Upw==)
    platform: mysql
    driver-class-name: com.mysql.jdbc.Driver

# 配置加密密钥
jasypt:
  encryptor:
    property:
      prefix: JASYPT_ZQ(   # TODO 加密前缀
      suffix: )            # TODO 加密后缀
    password: zhengqing    # TODO 加密密钥
